### ISSUE TITLE
I am getting black screen before loading the Map in Android.

### ISSUE THREAD

**Issue by TharaniP** [fysoul17/google_maps_place_picker#19] opened 2020-03-18 08:37 UTC
Hi fysoul17,
  Getting black screen before loading Map in android. But not facing this issue in ios. Please provide the solution.

Thanks in advance.

**Comment by fysoul17** [comment] 2020-03-18 10:45
Can you please use bug report? 
I cannot reproduce your case without providing any information.

**Comment by TharaniP** [comment] 2020-03-18 11:18
@fysoul17 

Steps to reproduce the behavior:
  Very first time, i can able to see the black screen (for very few seconds) before map loads on android devices. Second time onwards, map loads properly. 
  I think until map loads, black screen appears. Once its get loaded, next time onwards i could not see the black screen.

**Expected behavior**
In android devices, black screen should not come, before map loads.

**Comment by fysoul17** [comment] 2020-03-18 13:13
Please provide flutter doctor -v

**Comment by TharaniP** [comment] 2020-03-18 13:16
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/tharani/Documents/FlutterSDK/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tharani/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • SM A305F • RZ8M61SDBMJ • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by fysoul17** [comment] 2020-03-18 13:19
Thanks, @TharaniP 
Also please provide ```flutter run --verbose```  for the moment when the issue happens.
I still cannot reproduce it.

**Comment by TharaniP** [comment] 2020-03-18 13:48
mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
[  +34 ms] I/zzbz    (21256): Making Creator dynamically
[ +132 ms] W/Gralloc3(21256): allocator 3.x is not supported
[  +43 ms] W/""(21256): Unsupported class loader
[  +28 ms] I/DynamiteModule(21256): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:222
[        ] I/DynamiteModule(21256): Selected remote version of com.google.android.gms.maps_dynamite, version >= 222
[   +3 ms] V/DynamiteModule(21256): Dynamite loader version >= 2, using loadModule2NoCrashUtils
[  +97 ms] I/DynamiteLoaderV2(21256): [71] Mapsdynamite
[ +101 ms] I/Google Maps Android API(21256): Google Play services client version: 12451000
[  +10 ms] I/Google Maps Android API(21256): Google Play services package version: 200616037
[ +511 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[   +2 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
[   +2 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[  +13 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, linking, allowed)
[   +3 ms] W/""(21256): Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
[        ] W/""(21256): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
[  +30 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[   +8 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[   +1 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[ +284 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[   +4 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[   +1 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +14 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[   +2 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[   +1 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[   +8 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[  +26 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[  +10 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[  +15 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[   +3 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[  +61 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +15 ms] I/MultiWindowDecorSupport(21256): updateCaptionType >> DecorView@9239b78[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback:
false
[        ] D/MultiWindowDecorSupport(21256): setCaptionType = 0, DecorView = DecorView@9239b78[]
[  +16 ms] D/NetworkSecurityConfig(21256): No Network Security Config specified, using platform default
[   +2 ms] I/System.out(21256): (HTTPLog)-Static: isSBSettingEnabled false
[        ] I/System.out(21256): (HTTPLog)-Static: isSBSettingEnabled false
[   +6 ms] D/ViewRootImpl@2b71c42[MainActivity](21256): setView = com.android.internal.policy.DecorView@9239b78 TM=true MM=false
[  +37 ms] V/InputMethodManager(21256): Not IME target window, ignoring
[   +1 ms] D/SurfaceView(21256): onWindowVisibilityChanged(0) true com.google.maps.api.android.lib6.gmm6.api.au{18a3a61 VFE...C.. ......ID 0,0-0,0} of ViewRootImpl@2b71c42[MainActivity]
[  +21 ms] D/ViewRootImpl@2b71c42[MainActivity](21256): Relayout returned: old=(0,0,1080,2214) new=(0,0,1080,2214) req=(1080,2214)0 dur=15 res=0x7 s={true 507947532288} ch=true
[        ] D/OpenGLRenderer(21256): createReliableSurface : 0x75b321d9c0, 0x7644084000
[   +9 ms] D/mali_winsys(21256): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
[   +4 ms] D/SurfaceView(21256): surfaceCreated 1 #8 com.google.maps.api.android.lib6.gmm6.api.au{18a3a61 VFE...C.. ......ID 0,0-1080,2214}
[        ] D/SurfaceView(21256): surfaceChanged (1080,2214) 1 #8 com.google.maps.api.android.lib6.gmm6.api.au{18a3a61 VFE...C.. ......ID 0,0-1080,2214}
[        ] E/DecorView(21256): mWindow.mActivityCurrentConfig is null
[   +2 ms] D/mali_winsys(21256): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
[  +44 ms] D/ViewRootImpl@2b71c42[MainActivity](21256): Relayout returned: old=(0,0,1080,2214) new=(0,0,1080,2214) req=(1080,2214)0 dur=20 res=0x1 s={true 507947532288} ch=false
[   +6 ms] D/ViewRootImpl@2b71c42[MainActivity](21256): MSG_RESIZED: frame=(0,0,1080,2214) ci=(0,0,0,0) vi=(0,0,0,0) or=1
[  +64 ms] I/flutter (21256): null
[  +52 ms] I/flutter (21256): SafetyIncidentState
[        ] I/flutter (21256): Report Breakdown
[  +95 ms] I/flutter (21256): Selected Place Widget Builder
[  +63 ms] I/flutter (21256): State InitialState
[  +41 ms] I/flutter (21256): Error in Fetching images FileSystemException: Directory listing failed, path = '/data/user/0/…/‘ (OS Error: No
such file or directory, errno = 2)
[   +1 ms] I/flutter (21256): State LocalImagesState
[ +112 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[ +116 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[   +4 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[   +6 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +18 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[  +25 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[   +6 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[  +11 ms] I/""(21256): Background concurrent copying GC freed 27039(954KB) AllocSpace objects, 7(460KB) LOS objects, 49% free, 5577KB/10MB, paused 223us total 112.250ms
[   +3 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +10 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[  +20 ms] I/System.out(21256): (HTTPLog)-Static: isSBSettingEnabled false
[  +18 ms] I/System.out(21256): (HTTPLog)-Static: isSBSettingEnabled false
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[  +79 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[   +2 ms] W/""(""21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +17 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[  +65 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[ +400 ms] I/flutter (21256): Selected Place Widget Builder
[ +599 ms] W/DynamiteModule(21256): Local module descriptor class for com.google.android.gms.googlecertificates not found.
[  +20 ms] I/DynamiteModule(21256): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
[        ] I/DynamiteModule(21256): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
[  +19 ms] I/DynamiteLoaderV2(21256): [71] Googlecertificates
[  +87 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[  +17 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[   +1 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[  +20 ms] I/chatty  (21256): uid=10472(""4) androidmapsapi- identical 20 lines
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[  +75 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[   +6 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[  +16 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[   +7 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[   +5 ms] I/chatty  (21256): uid=10472(""4) GoogleApiHandle identical 1 line
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[   +1 ms] I/System.out(21256): (HTTPLog)-Static: isSBSettingEnabled false
[   +3 ms] I/System.out(21256): (HTTPLog)-Static: isSBSettingEnabled false
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[   +2 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[   +1 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[   +6 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[+1070 ms] I/chatty  (21256): uid=10472(""4) GoogleApiHandle identical 12 lines
[        ] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[+20566 ms] I/""(21256): Background concurrent copying GC freed 101806(3773KB) AllocSpace objects, 61(1976KB) LOS objects, 49% free, 4988KB/9977KB, paused 187us total 104.659ms
[+5691 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[+30823 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[+30271 ms] W/""(21256): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)

**Comment by TharaniP** [comment] 2020-03-24 10:21
@fysoul17 Can you able to reproduce the issue?

**Comment by fysoul17** [comment] 2020-03-25 09:56
Nope, I still cannot reproduce it. 

Since I am working on several different projects, please understand that I have not much time to look into the issue deeply. 

Once I get more free time, I will try more tests, but till then, please try to find out when it happens 100% then I can help more quickly.

**Comment by fysoul17** [comment] 2020-04-15 00:57
Closing as there is no further update. 
Please do not hesitate to re-open if you have a further issue.

**Closed by fysoul17** 2020-04-15 00:57 UTC
Labels: question
