### ISSUE TITLE
Dont kow why get this issue I hope you will help me out 

### ISSUE THREAD

**Issue by aTeamSolace** [fysoul17/google_maps_place_picker#38] opened 2020-05-19 04:40 UTC
**The plugin `google_api_availability` doesn't have a main class defined in E:\flutter_installation\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.4\android\src\main\java\com\baseflow\googleapiavailability\GoogleApiAvailabilityPlugin.java or E:\flutter_installation\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.4\android\src\main\kotlin\com\baseflow\googleapiavailability\GoogleApiAvailabilityPlugin.kt. This is likely to due to an incorrect `androidPackage: com.baseflow.googleapiavailability` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.** 

this error occured when i put this plugin in pubspec i also tried with flutter clean and fluttter upgread but not working ?

**Comment by fysoul17** [comment] 2020-05-20 15:07
This is duplicated with Issue #29.

**Comment by fysoul17** [comment] 2020-05-20 15:07
Duplicate of #29

**Closed** 2020-05-20 15:07 UTC
