### ISSUE TITLE
Don't know what is this issue exactly 

### ISSUE THREAD

**Issue by aTeamSolace** [fysoul17/google_maps_place_picker#29] opened 2020-04-20 13:34 UTC
The plugin `google_api_availability` doesn't have a main class defined in E:\flutter_installation\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.4\android\src\main\java\com\baseflow\googleapiavailability\GoogleApiAvailabilityPlugin.java or E:\flutter_installation\flutter\.pub-cache\hosted\pub.dartlang.org\google_api_availability-2.0.4\android\src\main\kotlin\com\baseflow\googleapiavailability\GoogleApiAvailabilityPlugin.kt. This is likely to due to an incorrect `androidPackage: com.baseflow.googleapiavailability` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.

**Comment by fysoul17** [comment] 2020-04-21 04:15
Hi @aTeamSolace ,

I think the package ```google_api_availability``` is related to ```geolocator``` package that is used by our package, and I checked geolocator and they updated version recently which seems because of the above issue.

Please update to version 0.9.4 and check if it is working as I updated geolocator's version to newest one in that version.

FYI, both google_api_availability and geolocator are 3rd party packages which means we are limited to handle issues related to it.

**Comment by aTeamSolace** [comment] 2020-04-21 06:24
hi @fysoul17, I updated version to 0.9.4 but still, this issue occurred. I also use flutter clean command and then flutter package get but still occurring.

**Comment by fysoul17** [comment] 2020-04-21 06:43
Have you tried with an empty project? 
I tried with a pure empty project and does not have any issue.

**Comment by aTeamSolace** [comment] 2020-04-21 06:48
no not with an empty project 
but I'm working on one client application actually this plugin is worked before some days version 0.9.0 and some changes I had done yesterday then this issue occurred 
well ill check, if it solved then okay else, will change code

**Comment by fysoul17** [comment] 2020-04-21 09:26
In the meantime, try to remove 'pubspec.lock' file and rebuild to see if it still happens.

**Comment by aTeamSolace** [comment] 2020-04-21 12:00
okok will check and let you know

**Comment by fysoul17** [comment] 2020-04-21 13:48
> actually issue occur with [google_map_location_picker](https://github.com/humazed/google_map_location_picker/issues) This plugin also

Yes, it is because that plugin also uses '''geolocator''' package. The error you are seeing is actually from geolocator package. 

I am sorry but I have no idea of what is happening there. 
Can you issue this to geolocator package side? I can't ask them since I cannot reproduce it.

**Comment by fysoul17** [comment] 2020-04-30 11:29
Closing as there is no further update. 
Please feel free to re-open if you have an update or an issue.

**Closed by fysoul17** 2020-04-30 11:29 UTC
