### ISSUE TITLE
selectedPlaceWidgetBuilder not updated after search if selectInitialPosition is true

### ISSUE THREAD

**Issue by ricardochen** [fysoul17/google_maps_place_picker#34] opened 2020-05-10 07:38 UTC
When selectInitialPosition is set to true,  selectedPlaceWidgetBuilder is not fired/updated after a search is made.

**To Reproduce**
set selectedPlaceWidgetBuilder to true
do a search and click on a result
**Expected behavior**
Updates map and  selectedPlaceWidgetBuilder

**Screenshots**

**Flutter Doctor -v**
[✓] Flutter (Channel master, 1.18.0-11.0.pre, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.18.0-11.0.pre at /Users/ricardochen/flutter/flutter
    • Framework revision 8568eda15b (4 days ago), 2020-05-05 16:10:41 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)
**Additional context**

**Comment by fysoul17** [comment] 2020-05-10 16:14
Hi, @ricardochen,

Unfortunately, I cannot reproduce it.
If you are using Mediaquery in selectedPlaceWidgetBuilder, Please refert to #30

**Comment by ricardochen** [comment] 2020-05-11 02:07
Yes it worked. Thanks

**Comment by fysoul17** [comment] 2020-05-11 03:06
No problem. 

Closing as the issue resolved.

**Closed by fysoul17** 2020-05-11 03:06 UTC
Labels: question
